StudentManagement/Models/Student.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Attends = new HashSet<Attend>();
        }
    
        public string id { get; set; }
        public string Name { get; set; }
        public bool Gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attend> Attends { get; set; }
    }
}

StudentManagement/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentManagement.Models;

namespace ManageStudent.Controllers
{
    public class StudentsController : Controller
    {
        private StudentManagementEntities db = new StudentManagementEntities();

        // GET: Students
        public ActionResult Index()
        {
            return View(db.Students.ToList());
        }
        public ActionResult StudentList(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(db.Attends.Where(x => x.id_Class == id).ToList());
        }
        [HttpPost]
        public ActionResult UpdateGrade(Attend grade)
        {

            String message;
            int status;
            try
            {
                //select ra thang attend
                Attend attend = db.Attends.Find(grade.id);
                attend.Grade = grade.Grade;
                db.SaveChanges();
                status = 1;
                message = "Thêm điểm thành công";
                

            }
            catch (Exception e)
            {
                status = 0;
                message = e.Message;
            }
            return Json(new { Status = status, Message = message, JsonRequestBehavior.AllowGet });
        }
        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Name,Gender")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Students.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(student);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Name,Gender")] Student student)
        {
            if (ModelState.IsValid)
            {
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentManagement/Views/Students/Create.cshtml
@model IEnumerable<StudentManagement.Models.Student>

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentManagement/Views/Students/Delete.cshtml
@model IEnumerable<StudentManagement.Models.Student>

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StudentManagement/Views/Students/Details.cshtml
@model ManageStudent.Models.Student

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StudentManagement/Views/Students/Edit.cshtml
@model ManageStudent.Models.Student

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentManagement/Views/Students/Index.cshtml
@model IEnumerable<StudentManagement.Models.Student>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Class </h2>

<p>
    @Html.ActionLink("New Student", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th></th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @*gender = true*@
            @*tương đương với dòng này if(item.Gender==true)*@
            @if (item.Gender)
            {
                <span>Name</span>
            }
            else
            {
                <span>Nữ</span>
            }

        </td>
        <td>@Html.ActionLink("Add Grade","InputView","Students")</td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    //function addgrade() {
    //    var obj = document.getElementById("btnGrade");
    //    obj. = 
    //}
    //function buttonClick() {

    //}
</script>

StudentManagement/Views/Students/InputView.cshtml
@model ManageStudent.Models.Attend

@{
    ViewBag.Title = "InputView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>InputView</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Attend</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_Student, "id_Student", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_Student", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_Student, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_Class, "id_Class", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_Class", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_Class, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grade2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grade2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentManagement/Views/Students/StudentList.cshtml
@model IEnumerable<StudentManagement.Models.Attend>

@{
    ViewBag.Title = "StudentList";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //so thu tu thoi
    var count = 1;
}

<h2>Index</h2>

<table class="table table-border">
    <tr class="head1">
        <th>No</th>
        <th>Name</th>
        <th>Gender</th>
        <th>Grade</th>
        <th>Action</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr class="head2">
            <th>@count</th>
            @{
                count++;
            }
            <td class="student-name" attendand-id="@item.id">
                @item.Student.Name
            </td>
            <td class="student-gender">
                @if (item.Student.Gender)
                {
                    <span>Nam</span>
                }
                else
                {
                    <span>Nữ</span>
                }

            </td>
            <td class="student-grade">@item.Grade</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>
<!--Modal-->
<div class="modal fade" id="modal-grade" role="dialog">
    <div class="modal-dialog modal-sm" style="width: 20%;">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <span class="modal-title" style="font-weight:bold;font-size:18px;">Add Grade</span>
            </div>
            <div class="modal-body" style="padding: 0px 20px;">
                <div class="form-group">
                    <label for="grade">Grade</label>
                    <input type="number" id="grade" class="form-control" min="0" max="10"/>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success btn-save">Save</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    function updateGrade(grade,cb) {
        $.ajax({
            url: '/Students/UpdateGrade/',
            type: 'post',
            data: { grade },
            dataType: "json",
            success: cb,
           
            error: function (err) {
                alert(err.statusText);
            },
        });
    }
    $(document).ready(function () {
        $('.btn-grade').on('click', function () {
            //get id attend
            id = $(this).parents('tr').find('.student-name').attr('attendand-id');
            //var obj = $("table").find("td").text()
            //trước khi show modal -> reset điểm về 0;
            $('#grade').val(0);
            $('#modal-grade').modal('show');
        });
        //viết sự kiện cho nut save
        $('.btn-save').on('click', function () {
            //lay gia tri grade
            //lay gia tri dung ham .val() nha 
            var value = $('#grade').val();

            //kiem tra xem co null hay khong
            if (value=='') {
                //nếu rỗng
                //báo lỗi
                alert('Điểm không được bỏ trống');
            } else if (value < 0 || value > 10) {
                alert('Nhập điểm lớn hơn không và nhỏ hơn 10');
            } else {
                //ajax update điểm trong attend
                //khúc ajax ngân làm dc ko?
                //:))
                //để update attendance cần id_attend chính là thằng id và thằng điểm chính là grade
                var grade = {
                    id: id,
                    Grade: value
                }
                updateGrade(grade);
                $('#modal-grade').modal('hide');
            }
        })
        var oldgrade,id;
        $('.student-grade').on('dblclick', function () {
            if (!$(this).hasClass('grade-active')) {
                id = $(this).parents('tr').find('.student-name').attr('attendand-id');
                oldgrade = $(this).html();
                $(this).html('');
                $(this).append('<input type="number" id="grade" class="form - control" min="0" max="10"/ value="' + oldgrade + '"><button class="btn btn-default btn-xs btn-grade-save">Save</button><button class="btn btn-danger btn-xs btn-grade-cancel">Cancel</button>');
                $(this).addClass('grade-active');    
            }
            
        })
        //save button 
        $('body').on('click', '.grade-active>.btn-grade-save', function () {
            var a = $(this);
            var value = $('#grade').val();
            var grade = {
                id: id,
                Grade: value
            }
            updateGrade(grade, function (data) {
                var status = parseInt(data['Status']);
                var message = data.Message;
                if (status == 1){
                    a.parents('.student-grade').html(grade.Grade).removeClass('grade-active');
                }
            });
        })
        //cancel button
        $('body').on('click', '.grade-active>.btn-grade-cancel', function () {
            $(this).parents('.student-grade').html(oldgrade).removeClass('grade-active');
        })
    });


</script>